"""
https://leetcode.com/problems/find-the-difference/description/
389. Find the Difference
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:
Input: s = "", t = "y"
Output: "y"
Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
"""
# Time - O(1 or n )

from collections import Counter


def findTheDifference(s: str, t: str) -> str:
    # count_s, count_t = Counter(s), Counter(t)
    # for c in count_t:
    #     if c not in count_s:
    #         return c
    #     if count_s[c] < count_t[c]:
    #         return c

    # sum_s, sum_t = 0, 0
    # for c in s:
    #     sum_s += ord(c)
    # for c in t:
    #     sum_t += ord(c)
    # return chr(sum_t - sum_s)

    res = 0
    for c in s:
        res = res ^ ord(c)
    for c in t:
        res = res ^ ord(c)

    return chr(res)


print(findTheDifference(s = "abcd", t = "abcde"))
print(findTheDifference(s = "", t = "y"))
